//! Regenerates the committed public-API surface snapshot
//! (`docs/public-api/fast-ssim2.txt`) on every `cargo test` run, so API
//! changes always show up as a git diff next to the code change that caused
//! them, and the surface size stays one glance away.
//!
//! Modes (`ZEN_API_DOC` env var — set per-job in CI workflows, see rust.yml):
//! - unset / `regen` → regenerate the file in place (local default; commit the diff)
//! - `check`         → regenerate to memory, FAIL if the committed file is stale
//! - `off`           → skipped (CI matrix jobs without nightly rustdoc / the tool)
//!
//! Requires `cargo-public-api` (0.52+) and a nightly toolchain for rustdoc
//! JSON: `cargo install cargo-public-api --locked && rustup toolchain install nightly`

use std::path::PathBuf;
use std::process::Command;

const CRATE: &str = "fast-ssim2";
/// Feature configurations captured in the snapshot, in file order.
/// (label, extra cargo-public-api args)
const CONFIGS: &[(&str, &[&str])] = &[
    ("default features", &[]),
    ("all features", &["--all-features"]),
];

fn surface(extra: &[&str]) -> Vec<String> {
    let mut cmd = Command::new("cargo");
    cmd.current_dir(env!("CARGO_MANIFEST_DIR"))
        .args(["public-api", "-p", CRATE, "--simplified"])
        .args(extra);
    let out = cmd.output().unwrap_or_else(|e| {
        panic!(
            "failed to run cargo public-api ({e}); install it with \
             `cargo install cargo-public-api --locked` and ensure a nightly \
             toolchain exists (`rustup toolchain install nightly`), or set \
             ZEN_API_DOC=off to skip this test"
        )
    });
    assert!(
        out.status.success(),
        "cargo public-api failed (set ZEN_API_DOC=off to skip):\n{}",
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout)
        .expect("cargo public-api emitted non-UTF8")
        .lines()
        .map(str::to_owned)
        .filter(|l| !l.is_empty())
        .collect()
}

#[test]
fn public_api_surface_doc_is_current() {
    match std::env::var("ZEN_API_DOC").as_deref() {
        Ok("off") => {
            eprintln!("ZEN_API_DOC=off — public-API snapshot regen skipped by caller");
            return;
        }
        Ok("check") | Ok("regen") | Err(_) => {}
        Ok(other) => panic!("unknown ZEN_API_DOC value {other:?} (off|check|regen)"),
    }

    let mut doc = String::new();
    doc.push_str(&format!(
        "# {CRATE} public API surface\n\
         # Generated by tests/public_api_doc.rs via `cargo public-api --simplified`\n\
         # (regenerated on every `cargo test`; ZEN_API_DOC=check verifies, =off skips).\n\
         # DO NOT EDIT BY HAND — commit regenerated changes together with the code.\n"
    ));
    for (label, extra) in CONFIGS {
        let items = surface(extra);
        doc.push_str(&format!("\n## {label} ({} items)\n\n", items.len()));
        for line in &items {
            doc.push_str(line);
            doc.push('\n');
        }
        eprintln!("{CRATE} [{label}]: {} public items", items.len());
    }

    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../docs/public-api")
        .join(format!("{CRATE}.txt"));
    let existing = std::fs::read_to_string(&path).ok();

    if std::env::var("ZEN_API_DOC").as_deref() == Ok("check") {
        assert_eq!(
            existing.as_deref(),
            Some(doc.as_str()),
            "committed public-API snapshot is stale: run `cargo test` locally \
             and commit the regenerated {}",
            path.display()
        );
        return;
    }

    if existing.as_deref() != Some(doc.as_str()) {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &doc).unwrap();
        eprintln!("regenerated {} — review and commit the diff", path.display());
    }
}
